svc1: vendor/bin/heroku-php-apache2 web/
svc2: vendor/bin/heroku-php-apache2 web/
svc3: vendor/bin/heroku-php-apache2 web/
svc4: vendor/bin/heroku-php-apache2 web/
svc5: vendor/bin/heroku-php-apache2 web/
svc6: vendor/bin/heroku-php-apache2 web/
svc7: vendor/bin/heroku-php-apache2 web/
svc8: vendor/bin/heroku-php-apache2 web/
svc9: vendor/bin/heroku-php-apache2 web/
svc10: vendor/bin/heroku-php-apache2 web/
svc11: vendor/bin/heroku-php-apache2 web/
svc12: vendor/bin/heroku-php-apache2 web/
svc13: vendor/bin/heroku-php-apache2 web/
svc14: vendor/bin/heroku-php-apache2 web/
svc15: vendor/bin/heroku-php-apache2 web/
svc16: vendor/bin/heroku-php-apache2 web/
svc17: vendor/bin/heroku-php-apache2 web/
svc18: vendor/bin/heroku-php-apache2 web/
svc19: vendor/bin/heroku-php-apache2 web/
svc20: vendor/bin/heroku-php-apache2 web/
svc21: vendor/bin/heroku-php-apache2 web/
svc22: vendor/bin/heroku-php-apache2 web/
svc23: vendor/bin/heroku-php-apache2 web/
svc24: vendor/bin/heroku-php-apache2 web/
svc25: vendor/bin/heroku-php-apache2 web/
